[Configuration]
LastHash = ""
Repo = "FreeRDP/FreeRDP"
Rpms = [ "gcc", "cmake", "ninja-build", "openssl-devel", "libX11-devel", "libXext-devel" ,"libXinerama-devel", "libXcursor-devel", "libXi-devel", "libXdamage-devel" ,"libXv-devel", "libxkbfile-devel", "alsa-lib-devel", "cups-devel", "ffmpeg-devel" ,"glib2-devel", "libusb-devel" ]
RpmsFolder = "C:\Code\C#\Fetcher\Fetcher\config.toml"
RepoPath = ""
RpmsZipPath = ""
BinariesPath = ""
BinariesZipPath = ""
