[Configuration]
LastHash = ""
Repo = "FreeRDP/FreeRDP"
# Rpms = [ "gcc", "cmake", "ninja-build", "openssl-devel", "libX11-devel", "libXext-devel" ,"libXinerama-devel", "libXcursor-devel", "libXi-devel", "libXdamage-devel" ,"libXv-devel", "libxkbfile-devel", "alsa-lib-devel", "cups-devel", "ffmpeg-devel" ,"glib2-devel", "libusb-devel" ]
Rpms = []
RepoPath = "C:\\Code\\fetcher\\progress\\repo.zip"
RpmsFolder = "C:\\Code\\C#\\fetcher\\rpms"
RpmsZipPath = "C:\\Code\\fetcher\\progress\\repo.zip"
BinariesPath = "C:\\Code\\fetcher\\progress"
BinariesZipPath = "C:\\Code\\fetcher\\ready"
