
[Configuration]
LastHash = "9867793d0751bb436c262d7d1cbb73346283fe59"
Repo = "FreeRDP/FreeRDP"
Rpms = []
RpmsFolder = "C:\\Code\\fetcher\\rpms"
RepoPath = "C:\\Code\\fetcher\\progress\\repo.zip"
RpmsZipPath = "C:\\Code\\fetcher\\progress\\rpms.zip"
BinariesPath = "C:\\Code\\fetcher\\progress"
BinariesZipPath = "C:\\Code\\fetcher\\ready\\binaries.zip"
